# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # Add ChannelIOSDK pod as required by channel_talk_flutter
  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/12.6.0/xcframework.podspec'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Flutter 필수 설정 유지
    flutter_additional_ios_build_settings(target)

    # permission_handler 권한 매크로 활성화
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']

      defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
      # 필요한 권한만 1로 켭니다 (없으면 추가)
      defs << 'PERMISSION_CONTACTS=1'
      defs << 'PERMISSION_MICROPHONE=1'

      # 쓰지 않는 권한은 굳이 넣지 않아도 되지만,
      # 명시적으로 0을 넣고 싶다면 예: defs << 'PERMISSION_CAMERA=0'
    end
  end
end